### ISSUE TITLE
Stm32

### ISSUE THREAD

**Issue by ciamia** [OpenCyphal/libcanard#199]
Hello, I want to send battery info to my autopilot orange cube from my stm32f405 based board. So far I was able to send data(bytes) to cube with can communication on Arduino IDE. I want to switch to UAVCAN but I dont know how. Can you help me please?

**Comment by pavel-kirienko** [comment]
UAVCAN no longer exists, the project is now called Cyphal. Start here:

- https://opencyphal.org/guide
- https://github.com/OpenCyphal/demos
