### ISSUE TITLE
Applying hardware acceptance filters

### ISSUE THREAD

**Issue by rebeccaRossRobotics** [OpenCyphal/libcanard#200]
Hello!

I'm currently attempting to implement acceptance filters into my application (which is based off the differential_pressure_sensor demo found [here](https://github.com/OpenCyphal-Garage/demos/tree/main/differential_pressure_sensor)). I've followed the explanation in the readme, using the API provided (canardMakeFilters and consolidateFilters functions). 

After using those functions it says to call `configureHardwareFilters(combined_config.extended_can_id, combined_config.extended_mask);`, however I cannot find any trace of this function within libcanard or socketcan. Is this something that I am meant to implement myself? 

I've looked back through the commits in libcanard to the point where the filters were added to the readme and the function doesn't exist there either.

Thank in advance

**Comment by pavel-kirienko** [comment]
>I cannot find any trace of this function within libcanard or socketcan. Is this something that I am meant to implement myself?

For SocketCAN you should use [`socketcanFilter()`](https://github.com/OpenCyphal-Garage/platform_specific_components/blob/de159248cdee0ee3ba5ac082809bc3b3b3413bf1/socketcan/libcanard/src/socketcan.h#L80), otherwise you may need to implement it yourself.
