### ISSUE TITLE
Extend api with `canardRxGetSubscription `

### ISSUE THREAD

**Issue by serges147** [OpenCyphal/libcanard#222]
c++ libcyphal needs api to detect already existing subscription (without "touching" one if any).
Here is proposal:
```
/// This function allows to check the effect of canardRxSubscribe() and canardRxUnsubscribe().
/// The return value is 1 if the specified subscription exists, 0 otherwise.
/// The return value is a negated invalid argument error if any of the input arguments are invalid.
int8_t canardRxGetSubscription(CanardInstance* const       ins,
                               const CanardTransferKind    transfer_kind,
                               const CanardPortID          port_id,
                               CanardRxSubscription* const out_subscription);
```

**Comment by serges147** [comment]
Looks like `canardRxHasSubscription() → bool` is enough - we only need to check for possible double subscription for the same kind & port pair.

**Comment by pavel-kirienko** [comment]
I actually wanted to mention this earlier but forgot: since we'll have to find that specific subscription in the tree anyway, should we not keep `canardRxGetSubscription` as it is more versatile? There are sensible use cases where one might want to find an existing subscription to modify it.

**Comment by serges147** [comment]
ok, I revert back to → `canardRxGetSubscription`
