### ISSUE TITLE
what is the relationship between this library and dronecan/libcanard?

### ISSUE THREAD

**Issue by zouzhe1** [OpenCyphal/libcanard#230]
what is the relationship between this library and dronecan/libcanard?

https://github.com/UAVCAN/libcanard
https://github.com/OpenCyphal/libcanard

https://github.com/dronecan/libcanard

**Comment by pavel-kirienko** [comment]
They all are based on the same original codebase but have since diverged. DroneCAN and Cyphal are distinct protocols; the differences are outlined here: https://forum.opencyphal.org/t/cyphal-vs-dronecan/1814
