### ISSUE TITLE
canardMakeFilterForSubject 

### ISSUE THREAD

**Issue by ambihelical** [OpenCyphal/libcanard#232]
The specification (section 4.2.1) says that bit 23 should be 0 for both subjects and services, yet canardMakeFilterForSubject does not create a filter that requires this bit to be 0 (that bit is not part of the mask).  Am I confused about something or is either the code or the spec wrong?

**Comment by pavel-kirienko** [comment]
This is done for forward compatibility. The bit is reserved and I'm not sure how it's going to be used in the future.
